name: TODO Checker

on:
  pull_request:

jobs:
  find-todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simple TODO Checker
        uses: damienjburks/simple-todo-checker@1.0.0
        with:
          path: "." # Scan default folder as this is required.
